name = "ButterFlyMatrixMPO"
uuid = "e4974282-f47c-4920-baad-a3ebf6911431"
authors = ["Karl Pierce <karl.m.pierce@gmail.com>"]
version = "0.0.1"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
ITensorCPD = "8ca0d870-8743-11ef-3aad-a3ebf6911431"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StridedViews = "4db3bf67-4bd7-4b4e-b153-31dc3fb37143"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
LinearAlgebra = "1.10.0"
julia = "1.10"